# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from corail.control.pb.control.v1 import control_pb2 as control_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """ControlService is the dedicated Recif <-> Corail communication channel.
    Always available on agent port 8001, regardless of agent channel type.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/control.v1.ControlService/Chat',
                request_serializer=control_dot_v1_dot_control__pb2.ChatRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/control.v1.ControlService/ChatStream',
                request_serializer=control_dot_v1_dot_control__pb2.ChatRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.ChatStreamEvent.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/control.v1.ControlService/ListConversations',
                request_serializer=control_dot_v1_dot_control__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/control.v1.ControlService/GetConversation',
                request_serializer=control_dot_v1_dot_control__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.GetConversationResponse.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/control.v1.ControlService/DeleteConversation',
                request_serializer=control_dot_v1_dot_control__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.DeleteConversationResponse.FromString,
                _registered_method=True)
        self.GetGenerationStatus = channel.unary_unary(
                '/control.v1.ControlService/GetGenerationStatus',
                request_serializer=control_dot_v1_dot_control__pb2.GetGenerationStatusRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.GetGenerationStatusResponse.FromString,
                _registered_method=True)
        self.ListMemories = channel.unary_unary(
                '/control.v1.ControlService/ListMemories',
                request_serializer=control_dot_v1_dot_control__pb2.ListMemoriesRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.ListMemoriesResponse.FromString,
                _registered_method=True)
        self.MemoryStatus = channel.unary_unary(
                '/control.v1.ControlService/MemoryStatus',
                request_serializer=control_dot_v1_dot_control__pb2.MemoryStatusRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.MemoryStatusResponse.FromString,
                _registered_method=True)
        self.StoreMemory = channel.unary_unary(
                '/control.v1.ControlService/StoreMemory',
                request_serializer=control_dot_v1_dot_control__pb2.StoreMemoryRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.StoreMemoryResponse.FromString,
                _registered_method=True)
        self.SearchMemories = channel.unary_unary(
                '/control.v1.ControlService/SearchMemories',
                request_serializer=control_dot_v1_dot_control__pb2.SearchMemoriesRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.SearchMemoriesResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/control.v1.ControlService/DeleteMemory',
                request_serializer=control_dot_v1_dot_control__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/control.v1.ControlService/GetStatus',
                request_serializer=control_dot_v1_dot_control__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/control.v1.ControlService/UpdateConfig',
                request_serializer=control_dot_v1_dot_control__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.UpdateConfigResponse.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/control.v1.ControlService/Reload',
                request_serializer=control_dot_v1_dot_control__pb2.ReloadRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/control.v1.ControlService/Pause',
                request_serializer=control_dot_v1_dot_control__pb2.PauseRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/control.v1.ControlService/Resume',
                request_serializer=control_dot_v1_dot_control__pb2.ResumeRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/control.v1.ControlService/StreamEvents',
                request_serializer=control_dot_v1_dot_control__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/control.v1.ControlService/Evaluate',
                request_serializer=control_dot_v1_dot_control__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/control.v1.ControlService/Health',
                request_serializer=control_dot_v1_dot_control__pb2.HealthRequest.SerializeToString,
                response_deserializer=control_dot_v1_dot_control__pb2.HealthResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """ControlService is the dedicated Recif <-> Corail communication channel.
    Always available on agent port 8001, regardless of agent channel type.
    """

    def Chat(self, request, context):
        """Chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """Conversations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenerationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemories(self, request, context):
        """Memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Agent control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Events stream (server -> client)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=control_dot_v1_dot_control__pb2.ChatRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=control_dot_v1_dot_control__pb2.ChatRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.ChatStreamEvent.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=control_dot_v1_dot_control__pb2.ListConversationsRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.ListConversationsResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=control_dot_v1_dot_control__pb2.GetConversationRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.GetConversationResponse.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=control_dot_v1_dot_control__pb2.DeleteConversationRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.DeleteConversationResponse.SerializeToString,
            ),
            'GetGenerationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenerationStatus,
                    request_deserializer=control_dot_v1_dot_control__pb2.GetGenerationStatusRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.GetGenerationStatusResponse.SerializeToString,
            ),
            'ListMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemories,
                    request_deserializer=control_dot_v1_dot_control__pb2.ListMemoriesRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.ListMemoriesResponse.SerializeToString,
            ),
            'MemoryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryStatus,
                    request_deserializer=control_dot_v1_dot_control__pb2.MemoryStatusRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.MemoryStatusResponse.SerializeToString,
            ),
            'StoreMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMemory,
                    request_deserializer=control_dot_v1_dot_control__pb2.StoreMemoryRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.StoreMemoryResponse.SerializeToString,
            ),
            'SearchMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemories,
                    request_deserializer=control_dot_v1_dot_control__pb2.SearchMemoriesRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.SearchMemoriesResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=control_dot_v1_dot_control__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=control_dot_v1_dot_control__pb2.GetStatusRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.GetStatusResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=control_dot_v1_dot_control__pb2.UpdateConfigRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.UpdateConfigResponse.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=control_dot_v1_dot_control__pb2.ReloadRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.ReloadResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=control_dot_v1_dot_control__pb2.PauseRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.PauseResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=control_dot_v1_dot_control__pb2.ResumeRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.ResumeResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=control_dot_v1_dot_control__pb2.StreamEventsRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.AgentEvent.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=control_dot_v1_dot_control__pb2.EvaluateRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.EvaluateResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=control_dot_v1_dot_control__pb2.HealthRequest.FromString,
                    response_serializer=control_dot_v1_dot_control__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """ControlService is the dedicated Recif <-> Corail communication channel.
    Always available on agent port 8001, regardless of agent channel type.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/Chat',
            control_dot_v1_dot_control__pb2.ChatRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/control.v1.ControlService/ChatStream',
            control_dot_v1_dot_control__pb2.ChatRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.ChatStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/ListConversations',
            control_dot_v1_dot_control__pb2.ListConversationsRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/GetConversation',
            control_dot_v1_dot_control__pb2.GetConversationRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.GetConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/DeleteConversation',
            control_dot_v1_dot_control__pb2.DeleteConversationRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.DeleteConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenerationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/GetGenerationStatus',
            control_dot_v1_dot_control__pb2.GetGenerationStatusRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.GetGenerationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/ListMemories',
            control_dot_v1_dot_control__pb2.ListMemoriesRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.ListMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/MemoryStatus',
            control_dot_v1_dot_control__pb2.MemoryStatusRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.MemoryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/StoreMemory',
            control_dot_v1_dot_control__pb2.StoreMemoryRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.StoreMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/SearchMemories',
            control_dot_v1_dot_control__pb2.SearchMemoriesRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.SearchMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/DeleteMemory',
            control_dot_v1_dot_control__pb2.DeleteMemoryRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/GetStatus',
            control_dot_v1_dot_control__pb2.GetStatusRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/UpdateConfig',
            control_dot_v1_dot_control__pb2.UpdateConfigRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.UpdateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/Reload',
            control_dot_v1_dot_control__pb2.ReloadRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/Pause',
            control_dot_v1_dot_control__pb2.PauseRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/Resume',
            control_dot_v1_dot_control__pb2.ResumeRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/control.v1.ControlService/StreamEvents',
            control_dot_v1_dot_control__pb2.StreamEventsRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/Evaluate',
            control_dot_v1_dot_control__pb2.EvaluateRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.v1.ControlService/Health',
            control_dot_v1_dot_control__pb2.HealthRequest.SerializeToString,
            control_dot_v1_dot_control__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
